#!/usr/bin/env bash

# Reveal the file/folder in the Finder.
#
# Usage:
#   reveal .                    # reveal the current folder
#   reveal ~/Desktop            # reveal a folder
#   reveal ~/Desktop/cat.jpg    # reveal a file
#

set -o errexit
set -o nounset

open -R "$@"
